### ISSUE TITLE
The demo files are not playing from the zip download

### ISSUE THREAD

**Issue by Morpheus0Neo** [mudcube/MIDI.js#63]
Hi,

This is a really amazing library but I facing some challenges in getting it to work.

I am really new to this stuff and have downloaded the source zip files twice.

The last time I downloaded the code zip, the demo files were playing when opened in chrome but they are not playing now. The colorful circles keeps going around and the soundfonts are never downloaded. The only message displayed is "Web Audio API...".
 
I happen to have the old zip and opening the the demo's from the old zip still works - the events and b64 midi plays when the demo files are opened in chrome.

In both cases the files are on my local machine and are not hosted on any server

So, do I need to make some changes that will get the latest version of demos playing?

Thanks for the help in advance.

Shantanu

**Comment by Kobld** [comment]
I dont know why this is closed. Your most basic example does not work **STILL**. The Ajax xhr request dies when this is downloaded as a zip. Why does this library need xhr and why doesn't this work?

**Comment by john02813** [comment]
I want to play happy birthday using basic.html but I am unable to play one note at a time as they all play at once.  I Placed 2 sets of code lines and it plays like a chord instead of 1 note then the next note.  How can I play notes to play a song?
<script type="text/javascript">
window.onload = function () 
{MIDI.loadPlugin({soundfontUrl: "./soundfont/",
instrument: "acoustic_grand_piano",
onprogress: function(state, progress) {
	console.log(state, progress);},
onsuccess: function() {	var delay = 0; // play one note every quarter second			
var note = 50; // the MIDI note			
var velocity = 127; // how hard the note hits
// play the note			
MIDI.setVolume(0, 127);			
MIDI.noteOn(0, note, velocity, delay);  
MIDI.noteOff(0, note, delay + 0.75);
note= 60;
MIDI.noteOn(0, note, velocity, delay);  
MIDI.noteOff(0, note, delay + 0.75);
});};



</script>

</body>

</html>

**Comment by shivrajsa** [comment]
@john02813 For last two notes you have same delay [ i.e.  delay + 0.75 ] , so both notes are playing at same time, change delay parameter for all notes, then they will be played at different interval. For example : delay , delay + 0.75, delay + 1 & so on
